name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Basic tests and linting
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.6.0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: |
        # Update lockfile if needed
        pnpm install --no-frozen-lockfile
        # Run audit but don't fail on moderate issues
        pnpm audit --audit-level high || true
      
    - name: Type check
      run: pnpm type-check
      
    - name: Lint check
      run: pnpm lint
      
    - name: Run unit tests
      run: pnpm test

  # Build verification
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.6.0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: |
        pnpm install --no-frozen-lockfile
        pnpm audit --audit-level high || true
      
    - name: Build application
      run: pnpm build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: .next/
        retention-days: 1

  # Security audit (separate job to avoid blocking main flow)
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true  # Don't fail the entire pipeline
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.6.0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: |
        pnpm install --no-frozen-lockfile
      
    - name: Security audit
      run: |
        echo "Running security audit..."
        pnpm audit --audit-level moderate || {
          echo "Security audit found issues, but continuing..."
          exit 0
        }

  # E2E Tests
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.6.0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: |
        pnpm install --no-frozen-lockfile
      
    - name: Install Playwright
      run: pnpm playwright install --with-deps
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .next/
      
    - name: Start application
      run: |
        pnpm start &
        # Wait for server to be ready
        pnpm wait-on http://localhost:3000 --timeout 60000
      
    - name: Run E2E tests
      run: pnpm test:e2e
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-results
        path: |
          test-results/
          playwright-report/
        retention-days: 7

  # Performance testing with Lighthouse
  lighthouse:
    name: Lighthouse Performance
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    continue-on-error: true  # Performance tests shouldn't block deployment
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.6.0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: |
        pnpm install --no-frozen-lockfile
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .next/
      
    - name: Start application
      run: |
        pnpm start &
        pnpm wait-on http://localhost:3000 --timeout 60000
      
    - name: Run Lighthouse CI
      run: |
        pnpm lighthouse --collect --upload.target=temporary-public-storage || {
          echo "Lighthouse failed but continuing..."
          exit 0
        }